version: "3"
services:
  pgdb:
    image: "postgres:11"
    container_name: "pg-multi-tenancy"
    ports:
      - "5432:5432"
    volumes:
      - multi-tenancy:/var/lib/postgresql/data
    networks:
      - postgres-compose-network
  pgadmin:
    image: dpage/pgadmin4
    container_name: "pgadmin-multi-tenancy"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "8888:80"
    depends_on:
      - pgdb
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge

volumes:
  multi-tenancy:


