server:
  port: 9876

spring:
  application:
    name: multi-tenancy
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password:
  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          lob:
            non_contextual_creation: true
